### ISSUE TITLE
make default.nix reproducable

### ISSUE THREAD

**Issue by garbas** [flyingcircusio/vulnix#4]
So we can be sure everybody works against the same version

## TODO

- [x] pin to specific nixpkgs revision
- [x] include nix expressions for python dependencies (generate from requirements.txt with pypi2nix)
- [x] create a release.nix to integrate hydra

**Comment by garbas** [comment]
fixed by #9
